### ISSUE TITLE
FS pack file requires image assets to be 320x240 pixels

### ISSUE THREAD

**Issue by alxbilger** [jersou/studio-pack-generator#21]
I have the following issue while trying to convert an archived produced by studio-pack-generator in Studio.

```
2023-07-27 16:45:57,193 [ERROR] [s.w.s.LibraryService]: Failed to convert archive format pack to FS format
java.lang.IllegalArgumentException: FS pack file requires image assets to be 320x240 pixels.
        at studio.core.v1.writer.fs.FsStoryPackWriter.write(FsStoryPackWriter.java:124)
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:322)
        at studio.webui.api.LibraryController$2.run(LibraryController.java:102)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
Exception in thread "Timer-0" java.lang.RuntimeException: Failed to convert archive format pack to FS format
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:332)
        at studio.webui.api.LibraryController$2.run(LibraryController.java:102)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: java.lang.IllegalArgumentException: FS pack file requires image assets to be 320x240 pixels.
        at studio.core.v1.writer.fs.FsStoryPackWriter.write(FsStoryPackWriter.java:124)
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:322)
        ... 3 more
```

And yet I don't see any image different from 320x240 in the zip.

To reproduce: 
```bash
studio-pack-generator-x86_64-windows.exe https://radiofrance-podcast.net/podcast09/rss_19721.xml
```

**Comment by jersou** [comment]
the new release [v0.2.9](https://github.com/jersou/studio-pack-generator/releases/tag/v0.2.9) convert the image files and it should fix your bug.
Re run SPG  on the "Oli" folder to fix images !

**Comment by alxbilger** [comment]
It works like a charm! Thank you so much for the responsiveness. You made a great tool. Keep it up!

**Comment by ioula76** [comment]
Hello,
I used the last version yesterday with Oli Podcast and some images are not converted in 320x240. The jpeg images. I deleted them from the .zip and I was able to transfer to the Lunii the stories.
